Impoved headings in search result(#478-headings-in-search)
vuestorefront/vsf-capybara pull request #479
Opened 2020-09-15 14:07 UTC by AishwaryShrivastav

Used sfui heading element instead of htm headings

### Related Issues

Closes #478 

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

Currently in the heading of search result, HTML, headings are used and then styling is applied on it to have expected UI
SFUI has its own heading component which will work fine here
Change html heading to sfui heading and corrected the styling around it. 

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2020-09-15 14:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DivanteLtd/vsf-capybara?pullRequest=479) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DivanteLtd/vsf-capybara?pullRequest=479) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DivanteLtd/vsf-capybara?pullRequest=479) it.</sub>

2020-09-18 15:04 UTC, AishwaryShrivastav commented
Many thanks to @dt2patel for suggesting these changes !!

2020-12-08 11:50 UTC, Fifciu requested changes
Okay, that's cool. Please just update a changelog

2020-12-22 13:04 UTC, Fifciu approved these changes

2020-12-22 13:10 UTC, merged