Improved: Spacing of elements of product page(#481)
vuestorefront/vsf-capybara pull request #483
Opened 2020-09-15 14:24 UTC by AishwaryShrivastav

Improved tab content padding top, review list padding, spacing of color label, product bottom.
Improved spacing around product info.

### Related Issues

Closes #481 

### Short Description and Why It's Useful

Improved tab content padding top, review list padding, spacing of color label, product bottom.
Improved spacing around product info.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2020-09-15 14:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DivanteLtd/vsf-capybara?pullRequest=483) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DivanteLtd/vsf-capybara?pullRequest=483) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DivanteLtd/vsf-capybara?pullRequest=483) it.</sub>

2020-09-18 15:00 UTC, AishwaryShrivastav commented
Many thanks to @dt2patel for suggesting these changes !!

2020-09-18 16:52 UTC, dt2patel commented
It's important to add that we did this so that in future if someone where to add new elements to the product_info section they don't have to remember to add a horizontal margin to it. Instead, by having padding defined on the parent component, even though padding is doubled up on the tabs, the experience of adding components and elements to the product_info section is smoother and leaves less room for error.

2020-12-08 11:57 UTC, Fifciu requested changes
Sounds cool. Please just update the changelog

2021-01-04 08:54 UTC, Fifciu approved these changes

2021-01-04 08:55 UTC, merged