Improved: Use of spacing variables in padding for social icon(#484)
vuestorefront/vsf-capybara pull request #485
Opened 2020-09-15 14:33 UTC by AishwaryShrivastav

Instead of hard coded values we used the defined variables for the spacing.

### Related Issues

Closes #484 

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2020-09-15 14:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DivanteLtd/vsf-capybara?pullRequest=485) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DivanteLtd/vsf-capybara?pullRequest=485) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DivanteLtd/vsf-capybara?pullRequest=485) it.</sub>

2020-09-18 14:54 UTC, AishwaryShrivastav commented
Many thanks to @dt2patel for suggesting these changes !!

2020-12-08 12:07 UTC, Fifciu requested changes
Great but changelog please

2021-01-04 08:56 UTC, Fifciu approved these changes

2021-01-04 08:56 UTC, merged