Improved: the code to fix the error of undefined on the product page (#549)
vuestorefront/vsf-capybara pull request #550
Opened 2020-11-28 04:53 UTC by ymaheshwari1

### Related Issues
#549 

Closes #549 

### Short Description and Why It's Useful
The changes will help to remove the console error related to undefined.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2020-12-08 12:49 UTC, Fifciu approved these changes

2020-12-08 12:49 UTC, Fifciu requested changes
Please update the changelog

2021-01-07 14:22 UTC, ymaheshwari1 commented
Maintained the changelog for the PR here: https://github.com/vuestorefront/vsf-capybara/pull/573

2021-01-07 14:29 UTC, Fifciu approved these changes

2021-01-07 14:29 UTC, merged